/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var imageManager = require('../lib/image_transfer').sharedManager;

var atob = window.atob;

// We don't get atob on iOS, so provide our own implementation.
// This code was generated by Google Search, in response to the query "atob in pure javascript".
// It seems to work.
if (!atob) {
    atob = function(encoded) {
        const base64 =
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
        var str = "";
        var bytes = 0;
        var bits = 0;
        for (var i = 0; i < encoded.length; i++) {
            const char = encoded.charAt(i);
            if (char === "=") {
                break;
            }
            var value = base64.indexOf(char);
            if (value < 0) {
                continue;
            }
            bytes = (bytes << 6) | value;
            bits += 6;
            if (bits >= 8) {
                str += String.fromCharCode((bytes >>> (bits - 8)) & 255);
                bits -= 8;
            }
        }
        return str;
    }
}

exports.map = function(session, params) {
    console.log(JSON.stringify(params));
    var base64pbi = params['image'];
    var width = params['width'];
    var height = params['height'];
    var pbi = atob(base64pbi);
    var imageData = new Array(pbi.length);
    for (var i = 0; i < pbi.length; i++) {
        imageData[i] = pbi.charCodeAt(i);
    }
    var imageId = imageManager.sendImage(width, height, imageData);
    var userLocation = 0;
    if (params['user_location_x'] && params['user_location_y']) {
        userLocation = (params['user_location_x'] << 16) | params['user_location_y'];
    }
    var message = {
        MAP_WIDGET: 1,
        MAP_WIDGET_IMAGE_ID: imageId,
        MAP_WIDGET_USER_LOCATION: userLocation
    };
    console.log(JSON.stringify(message));
    session.enqueue(message);
}
